Here is a project to detect "לשון הרע "

In [ ]:
#%pip install pandas

In [1]:
from google.colab import files

# This will open a file picker in Colab
uploaded = files.upload()

Saving training.1600000.processed.noemoticon.csv to training.1600000.processed.noemoticon.csv

Here we load the dataset
The dataset is available at https://www.kaggle.com/datasets/ferno2/training1600000processednoemoticoncsv

In [2]:
from google.colab import drive

# Mount Google Drive
drive.mount('/content/drive')

Mounted at /content/drive

In [4]:
from google.colab import files
import shutil

# Upload the file from your local system
# uploaded = files.upload()

# Move the uploaded file to your Google Drive folder
file_name = "training.1600000.processed.noemoticon.csv"  # Get the file name from the uploaded dict
drive_folder = '/content/drive/MyDrive/deep_learning/'  # Specify the folder path in your Google Drive
shutil.move(file_name, drive_folder + file_name)

print(f"File saved to {drive_folder}{file_name}")

File saved to /content/drive/MyDrive/deep_learning/training.1600000.processed.noemoticon.csv

In [5]:
import pandas as pd

# Path to your file on Google Drive
file_path = '/content/drive/MyDrive/deep_learning/training.1600000.processed.noemoticon.csv'

# Load the data
df = pd.read_csv(file_path, encoding='ISO-8859-1')

# Preview the data
df.head()

,0,1467810369,Mon Apr 06 22:19:45 PDT 2009,NO_QUERY,_TheSpecialOne_,"@switchfoot http://twitpic.com/2y1zl - Awww, that's a bummer. You shoulda got David Carr of Third Day to do it. ;D"
0,0,1467810672,Mon Apr 06 22:19:49 PDT 2009,NO_QUERY,scotthamilton,is upset that he can't update his Facebook by ...
1,0,1467810917,Mon Apr 06 22:19:53 PDT 2009,NO_QUERY,mattycus,@Kenichan I dived many times for the ball. Man...
2,0,1467811184,Mon Apr 06 22:19:57 PDT 2009,NO_QUERY,ElleCTF,my whole body feels itchy and like its on fire
3,0,1467811193,Mon Apr 06 22:19:57 PDT 2009,NO_QUERY,Karoli,"@nationwideclass no, it's not behaving at all...."
4,0,1467811372,Mon Apr 06 22:20:00 PDT 2009,NO_QUERY,joy_wolf,@Kwesidei not the whole crew

In [2]:
# import pandas as pd

# # # Define column names based on the dataset documentation
# # columns = ["target", "ids", "date", "flag", "user", "text"]

# # Load the file (Colab stores it in the current working directory)
# df = pd.read_csv("training.1600000.processed.noemoticon.csv", encoding='ISO-8859-1')

# # Preview the data
# df.head()

FileNotFoundError: [Errno 2] No such file or directory: 'training.1600000.processed.noemoticon.csv'

In [1]:

# import pandas as pd

# df = pd.read_csv('./training.1600000.processed.noemoticon.csv', encoding='ISO-8859-1')
# df.head()

FileNotFoundError: [Errno 2] No such file or directory: './training.1600000.processed.noemoticon.csv'

Here we will add columns names:

In [6]:
df.columns = ['sentiment', 'id', 'date', 'query', 'user', 'text']
df.head()

,sentiment,id,date,query,user,text
0,0,1467810672,Mon Apr 06 22:19:49 PDT 2009,NO_QUERY,scotthamilton,is upset that he can't update his Facebook by ...
1,0,1467810917,Mon Apr 06 22:19:53 PDT 2009,NO_QUERY,mattycus,@Kenichan I dived many times for the ball. Man...
2,0,1467811184,Mon Apr 06 22:19:57 PDT 2009,NO_QUERY,ElleCTF,my whole body feels itchy and like its on fire
3,0,1467811193,Mon Apr 06 22:19:57 PDT 2009,NO_QUERY,Karoli,"@nationwideclass no, it's not behaving at all...."
4,0,1467811372,Mon Apr 06 22:20:00 PDT 2009,NO_QUERY,joy_wolf,@Kwesidei not the whole crew

Why do we need 'query' column?

In [7]:
# Here we will check the different values in the 'query' column:
print(df['query'].unique())

['NO_QUERY']

It only has one value, so we can drop this column,
but first we will copy the dateset:

In [8]:
data = df.copy()
data = data.drop(columns=['query'])
data.head()

,sentiment,id,date,user,text
0,0,1467810672,Mon Apr 06 22:19:49 PDT 2009,scotthamilton,is upset that he can't update his Facebook by ...
1,0,1467810917,Mon Apr 06 22:19:53 PDT 2009,mattycus,@Kenichan I dived many times for the ball. Man...
2,0,1467811184,Mon Apr 06 22:19:57 PDT 2009,ElleCTF,my whole body feels itchy and like its on fire
3,0,1467811193,Mon Apr 06 22:19:57 PDT 2009,Karoli,"@nationwideclass no, it's not behaving at all...."
4,0,1467811372,Mon Apr 06 22:20:00 PDT 2009,joy_wolf,@Kwesidei not the whole crew

Same for the id column, we don't think it can help to tell if a given text is לשון הרע or not:

In [9]:
data = data.drop(columns=['id'])
data.head()

,sentiment,date,user,text
0,0,Mon Apr 06 22:19:49 PDT 2009,scotthamilton,is upset that he can't update his Facebook by ...
1,0,Mon Apr 06 22:19:53 PDT 2009,mattycus,@Kenichan I dived many times for the ball. Man...
2,0,Mon Apr 06 22:19:57 PDT 2009,ElleCTF,my whole body feels itchy and like its on fire
3,0,Mon Apr 06 22:19:57 PDT 2009,Karoli,"@nationwideclass no, it's not behaving at all...."
4,0,Mon Apr 06 22:20:00 PDT 2009,joy_wolf,@Kwesidei not the whole crew

Here we will check the amount of rows of each type:
0 - negative text
1 - positive text

In [10]:
print(data['sentiment'].value_counts().loc[[0, 4]])

sentiment
0    799999
4    800000
Name: count, dtype: int64

In [11]:
print("Example with sentiment 0:")
print(data[data['sentiment'] == 0].iloc[0])

print("\nExample with sentiment 4:")
print(data[data['sentiment'] == 4].iloc[0])

Example with sentiment 0:
sentiment                                                    0
date                              Mon Apr 06 22:19:49 PDT 2009
user                                             scotthamilton
text         is upset that he can't update his Facebook by ...
Name: 0, dtype: object

Example with sentiment 4:
sentiment                                               4
date                         Mon Apr 06 22:22:45 PDT 2009
user                                                ersle
text         I LOVE @Health4UandPets u guys r the best!!
Name: 799999, dtype: object

to do - Check if rows with label are affected by the time?
is text written late at night probably labeled negative ?

We assume that rows labeled 0 that mentions someone else, are more likely to be לשון הרע  for example:
 0 - "@nationwideclass no, it's not behaving at all...."  - לשון הרע
 0 - "my whole body feels itchy and like its on fire" - לא לשון הרע

So here we go and filter all rows that are negative sentiment (labeled 0) and contains '@'

In [12]:
neg_with_mentions = data[(data['sentiment'] == 0) & (data['text'].str.contains('@'))]
print("Number of negative tweets with mentions:", len(neg_with_mentions))

Number of negative tweets with mentions: 305210

About half from the data set with labeled 0

now we can get text like this: "@Kwesidei not the whole crew" - its negative but not לשון הרע

So now we will find the text that are not only negative but also insulting or offensive.
We do that by creating a list a not good words that if where in a sentence and mention some one we will say the sentence will be לשון הרע

In [13]:
keywords = [
    'stupid',
    'hate',
    'hates',
    'hate this',
    'hates that',
    'cry',
    'idiot',
    'idiots',
    'worst',
    'annoying',
    'ugly',
    'terrible',
    'awful',
    'horrible',
    'horrid',
    'dislike',
    'disgusting',
    'disgusted',
    'disappointed',
    'liar',
    'bad',
    'dumb',
    'fool',
    'foolish',
    'not good',
    'not great',
    'not ok',
    'not okay',
    'not nice',
    'not like',
    'not happy',
    'upset',
    'iam angry',
    'angry',
    ]

personal_references = ['@', 'he', 'she', 'you', 'your', 'his', 'her', 'them']

In [14]:
def is_weak_lashon(text):
    text = text.lower()
    return any(word in text for word in keywords)

data['lashon_hara_guess'] = data.apply(
    lambda row: int(row['sentiment'] == 0 and any(word in row['text'] for word in personal_references) and is_weak_lashon(row['text'])),
    axis=1
)

Lets see the dataset now:

In [15]:
data.head()

,sentiment,date,user,text,lashon_hara_guess
0,0,Mon Apr 06 22:19:49 PDT 2009,scotthamilton,is upset that he can't update his Facebook by ...,1
1,0,Mon Apr 06 22:19:53 PDT 2009,mattycus,@Kenichan I dived many times for the ball. Man...,0
2,0,Mon Apr 06 22:19:57 PDT 2009,ElleCTF,my whole body feels itchy and like its on fire,0
3,0,Mon Apr 06 22:19:57 PDT 2009,Karoli,"@nationwideclass no, it's not behaving at all....",0
4,0,Mon Apr 06 22:20:00 PDT 2009,joy_wolf,@Kwesidei not the whole crew,0

Lets make sure that the data set are balanced:

In [16]:
data['lashon_hara_guess'].value_counts()
# 1 = likely Lashon Hara, 0 = unlikely

lashon_hara_guess
0    1544726
1      55273
Name: count, dtype: int64

Here we have more rows with labels 0.
To have the same amount of data for 0 and for 1

In [17]:
# Separate the two classes
class_0 = data[data['lashon_hara_guess'] == 0]
class_1 = data[data['lashon_hara_guess'] == 1]

# Downsample the majority class
min_count = min(len(class_0), len(class_1))
class_0_balanced = class_0.sample(n=min_count, random_state=42)
class_1_balanced = class_1.sample(n=min_count, random_state=42)

# Combine and shuffle
balanced_data = pd.concat([class_0_balanced, class_1_balanced]).sample(frac=1, random_state=42).reset_index(drop=True)
print(balanced_data['lashon_hara_guess'].value_counts())

lashon_hara_guess
1    55273
0    55273
Name: count, dtype: int64

In [18]:
print("Example with sentiment 1 - likely:")
balanced_data[balanced_data['lashon_hara_guess'] == 1].sample()[['text']]['text'].values[0]

Example with sentiment 1 - likely:

"my phone hates your tweets  i'm only getting like half of them  turning off device updates for a bit"

In [19]:
print("Example with sentiment 0 - unlikely:")
balanced_data[balanced_data['lashon_hara_guess'] == 0].sample()[['text']]['text'].values[0]

Example with sentiment 0 - unlikely:

'trying to find something to cure me of my boredom '

Problem: this data is not really לשון הרע
or filter it better or find a different data set !!!!!!!!!!!!!!!!!!!!

So were going to try a few methods:
- ML
- Deep learning
- Transformers

then compare the results:

--  Machine Learning --
We used a logistic Regression classifier
Why It's Good:
- Fast to train
- Interpretable (you can inspect weights)
- Surprisingly effective for text tasks

In [20]:
# %pip install scikit-learn

In [21]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report

# 1. Load your existing DataFrame
# (assuming df already has 'text' and 'lashon_hara_guess' columns)

# 2. Prepare features and labels
X = balanced_data['text']
y = balanced_data['lashon_hara_guess']

# 3. Split into train and test sets
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

# 4. Convert text to TF-IDF features
vectorizer = TfidfVectorizer(max_features=5000, ngram_range=(1,2), stop_words='english')
X_train_vec = vectorizer.fit_transform(X_train)
X_test_vec = vectorizer.transform(X_test)

# 5. Train a Logistic Regression model
model = LogisticRegression()
model.fit(X_train_vec, y_train)

# 6. Predict on the test set
y_pred = model.predict(X_test_vec)

# 7. Evaluate
print(classification_report(y_test, y_pred, target_names=["Not Lashon Hara", "Lashon Hara"]))

                 precision    recall  f1-score   support

Not Lashon Hara       0.88      0.97      0.92     11055
    Lashon Hara       0.96      0.86      0.91     11055

       accuracy                           0.92     22110
      macro avg       0.92      0.92      0.91     22110
   weighted avg       0.92      0.92      0.91     22110

In [22]:
def predict_lashon_hara(text):
    vec = vectorizer.transform([text])
    pred = model.predict(vec)[0]
    return "Lashon Hara" if pred == 1 else "Not Lashon Hara"

# Try it!
print(predict_lashon_hara("@john you're such an idiot"))

Lashon Hara

-- Deep learning --
Recurrent Neural Network (RNN) – Text classifier using Keras (TensorFlow) with an embedding layer, LSTM, and Dense layers
It's more powerful than models like logistic regression or simple feedforward networks
because it can learn temporal dependencies, like:
Text:
“@david wow you're just the smartest guy in the room 🙄”

LSTM will think:
It captures the sarcasm from context and emoji.
Logistic regression:
might be fooled by the word "smartest".

In [23]:
# %pip install tensorflow

In [24]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense, Dropout
from tensorflow.keras.utils import to_categorical

# 1. Prepare Data
X = balanced_data['text'].values
y = balanced_data['lashon_hara_guess'].values

# 2. Split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, stratify=y, random_state=42
)

# 3. Tokenize & Pad
vocab_size = 10000
maxlen = 50

tokenizer = Tokenizer(num_words=vocab_size, oov_token='<OOV>')
tokenizer.fit_on_texts(X_train)

X_train_seq = tokenizer.texts_to_sequences(X_train)
X_test_seq = tokenizer.texts_to_sequences(X_test)

X_train_pad = pad_sequences(X_train_seq, maxlen=maxlen, padding='post', truncating='post')
X_test_pad = pad_sequences(X_test_seq, maxlen=maxlen, padding='post', truncating='post')

# 4. Model
model = Sequential([
    Embedding(input_dim=vocab_size, output_dim=128, input_length=maxlen),
    LSTM(64, return_sequences=False),
    Dropout(0.3),
    Dense(32, activation='relu'),
    Dropout(0.2),
    Dense(1, activation='sigmoid')  # Binary classification
])

model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

# 5. Train
model.fit(X_train_pad, y_train, epochs=5, batch_size=64, validation_split=0.1)

# 6. Evaluate
loss, acc = model.evaluate(X_test_pad, y_test)
print(f"Test Accuracy: {acc:.4f}")

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(

Epoch 1/5
1244/1244 ━━━━━━━━━━━━━━━━━━━━ 18s 9ms/step - accuracy: 0.7636 - loss: 0.4164 - val_accuracy: 0.9727 - val_loss: 0.1223
Epoch 2/5
1244/1244 ━━━━━━━━━━━━━━━━━━━━ 16s 9ms/step - accuracy: 0.9701 - loss: 0.1323 - val_accuracy: 0.9731 - val_loss: 0.1155
Epoch 3/5
1244/1244 ━━━━━━━━━━━━━━━━━━━━ 21s 9ms/step - accuracy: 0.9719 - loss: 0.1196 - val_accuracy: 0.9739 - val_loss: 0.1137
Epoch 4/5
1244/1244 ━━━━━━━━━━━━━━━━━━━━ 26s 13ms/step - accuracy: 0.9731 - loss: 0.1052 - val_accuracy: 0.9740 - val_loss: 0.1243
Epoch 5/5
1244/1244 ━━━━━━━━━━━━━━━━━━━━ 9s 8ms/step - accuracy: 0.9753 - loss: 0.0883 - val_accuracy: 0.9716 - val_loss: 0.1291
691/691 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.9687 - loss: 0.1422
Test Accuracy: 0.9675

Accuracy: 0.8866

In [25]:
# Example 1:
print("@dude you're such a liar and an idiot")
print(predict_lashon_hara("@dude you're such a liar and an idiot"))

print("\n")
# Example 2:
print("@dude you're such a liar")
print(predict_lashon_hara("@dude you're such a liar"))

@dude you're such a liar and an idiot
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 411ms/step
Not Lashon Hara


@dude you're such a liar
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 173ms/step
Not Lashon Hara

-- DM modal: Embedding + Global Average Pooling + Dense (MLP) --
GlobalAveragePooling1D - Averages all word embeddings into a single vector
Suppose you have a sentence of 5 words, and each word is represented by a 4-dimensional embedding:

[
 [0.1, 0.2, 0.3, 0.4],  ← word 1
 [0.5, 0.1, 0.0, 0.3],  ← word 2
 [0.2, 0.3, 0.5, 0.2],  ← word 3
 [0.0, 0.1, 0.2, 0.1],  ← word 4
 [0.1, 0.2, 0.2, 0.3]   ← word 5
]
GlobalAveragePooling1D takes the average across all rows, like this:

mean of each column = [
 (0.1+0.5+0.2+0.0+0.1)/5 = 0.18,
 (0.2+0.1+0.3+0.1+0.2)/5 = 0.18,
 (0.3+0.0+0.5+0.2+0.2)/5 = 0.24,
 (0.4+0.3+0.2+0.1+0.3)/5 = 0.26
]
So now your sentence becomes just one vector of 4 numbers, not 5 vectors of 4:
→ [0.18, 0.18, 0.24, 0.26]

advantages:
- Much faster than LSTM
- Captures general topic/word presence but not word order
- Good for short, simple sentences or when you don’t need context modeling

| Feature              | This Model         | LSTM                         |
| -------------------- | ------------------ | ---------------------------  |
| Captures word order? | ❌ No              | ✅ Yes                      |
| Training speed       | ⚡ Fast            | 🐢 Slower                   |
| Accuracy potential   | 😐 Medium          | 🔥 Higher (on complex data) |
| Complexity           | 🟢 Simple          | 🔴 More complex             |

In [26]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, GlobalAveragePooling1D, Dense, Dropout

# 1. Prepare Data
X = balanced_data['text'].values
y = balanced_data['lashon_hara_guess'].values

# 2. Split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, stratify=y, random_state=42
)

# 3. Tokenize & Pad
vocab_size = 10000
maxlen = 50

tokenizer = Tokenizer(num_words=vocab_size, oov_token='<OOV>')
tokenizer.fit_on_texts(X_train)

X_train_seq = tokenizer.texts_to_sequences(X_train)
X_test_seq = tokenizer.texts_to_sequences(X_test)

X_train_pad = pad_sequences(X_train_seq, maxlen=maxlen, padding='post', truncating='post')
X_test_pad = pad_sequences(X_test_seq, maxlen=maxlen, padding='post', truncating='post')

# 4. Model

model = Sequential([
    Embedding(input_dim=vocab_size, output_dim=128, input_length=maxlen),
    GlobalAveragePooling1D(),  # turns 2D sequences into flat vector
    Dense(128, activation='relu'),
    Dropout(0.3),
    Dense(64, activation='relu'),
    Dropout(0.2),
    Dense(1, activation='sigmoid')
])


model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# 5. Train
model.fit(X_train_pad, y_train, epochs=5, batch_size=64, validation_split=0.1)

# 6. Evaluate
loss, acc = model.evaluate(X_test_pad, y_test)
print(f"Test Accuracy: {acc:.4f}")

Epoch 1/5

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(

1244/1244 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - accuracy: 0.7783 - loss: 0.4200 - val_accuracy: 0.9534 - val_loss: 0.1550
Epoch 2/5
1244/1244 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - accuracy: 0.9536 - loss: 0.1553 - val_accuracy: 0.9524 - val_loss: 0.1533
Epoch 3/5
1244/1244 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.9606 - loss: 0.1383 - val_accuracy: 0.9534 - val_loss: 0.1497
Epoch 4/5
1244/1244 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.9628 - loss: 0.1239 - val_accuracy: 0.9583 - val_loss: 0.1480
Epoch 5/5
1244/1244 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9652 - loss: 0.1127 - val_accuracy: 0.9406 - val_loss: 0.1986
691/691 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.9385 - loss: 0.2058
Test Accuracy: 0.9386

-- DL: Multilayer Perceptron (MLP) for Text Classification --
Model Type:
A fully connected feedforward neural network
No awareness of word order or sequence, just uses numerical input vectors

Uses TfidfVectorizer - Converts text into a flat vector of word/token importance (no word order)

In [28]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split

# 1. Prepare Data
X = balanced_data['text'].values
y = balanced_data['lashon_hara_guess'].values

# 2. Split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, stratify=y, random_state=42)

# 3. TF-IDF
vectorizer = TfidfVectorizer(max_features=5000)
X_train_vec = vectorizer.fit_transform(X_train).toarray()
X_test_vec = vectorizer.transform(X_test).toarray()

# 4. MLP Model
model = Sequential([
    Dense(128, activation='relu', input_shape=(X_train_vec.shape[1],)),
    Dropout(0.3),
    Dense(64, activation='relu'),
    Dropout(0.2),
    Dense(1, activation='sigmoid')
])

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# 5. Train
model.fit(X_train_vec, y_train, epochs=5, batch_size=64, validation_split=0.1)

# 6. Evaluate
loss, acc = model.evaluate(X_test_vec, y_test)
print(f"Test Accuracy: {acc:.4f}")

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Epoch 1/5
1244/1244 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - accuracy: 0.8452 - loss: 0.3532 - val_accuracy: 0.9565 - val_loss: 0.1566
Epoch 2/5
1244/1244 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - accuracy: 0.9575 - loss: 0.1519 - val_accuracy: 0.9603 - val_loss: 0.1488
Epoch 3/5
1244/1244 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.9661 - loss: 0.1179 - val_accuracy: 0.9622 - val_loss: 0.1481
Epoch 4/5
1244/1244 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.9711 - loss: 0.0940 - val_accuracy: 0.9610 - val_loss: 0.1620
Epoch 5/5
1244/1244 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.9780 - loss: 0.0675 - val_accuracy: 0.9591 - val_loss: 0.1894
691/691 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.9517 - loss: 0.2210
Test Accuracy: 0.9515

-- DL: CNN --

A 1D CNN designed to detect local patterns in sequences of word embeddings for text classification

Summary Table

| Feature                   | CNN for Text  |
| ------------------------- | ------------  |
| Learns word order?        | ✅ (local)    |
| Good for sarcasm/context? | ❌ Limited    |
| Great for phrase patterns | ✅ Yes        |
| Requires padding & tokens | ✅ Yes        |
| Training speed            | ⚡ Fast       |

In [29]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, Conv1D, GlobalMaxPooling1D, Dense

model = Sequential([
    Embedding(input_dim=vocab_size, output_dim=128, input_length=maxlen),
    Conv1D(128, kernel_size=5, activation='relu'),
    GlobalMaxPooling1D(),
    Dense(64, activation='relu'),
    Dense(1, activation='sigmoid')
])
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

model.fit(X_train_pad, y_train, epochs=5, batch_size=64, validation_split=0.1)

loss, acc = model.evaluate(X_test_pad, y_test)
print(f"Test Accuracy: {acc:.4f}")

Epoch 1/5

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(

1244/1244 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - accuracy: 0.9058 - loss: 0.2416 - val_accuracy: 0.9756 - val_loss: 0.1108
Epoch 2/5
1244/1244 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - accuracy: 0.9722 - loss: 0.1004 - val_accuracy: 0.9729 - val_loss: 0.1143
Epoch 3/5
1244/1244 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - accuracy: 0.9819 - loss: 0.0556 - val_accuracy: 0.9679 - val_loss: 0.1520
Epoch 4/5
1244/1244 ━━━━━━━━━━━━━━━━━━━━ 8s 7ms/step - accuracy: 0.9930 - loss: 0.0235 - val_accuracy: 0.9656 - val_loss: 0.1718
Epoch 5/5
1244/1244 ━━━━━━━━━━━━━━━━━━━━ 9s 7ms/step - accuracy: 0.9970 - loss: 0.0100 - val_accuracy: 0.9675 - val_loss: 0.2193
691/691 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - accuracy: 0.9651 - loss: 0.2469
Test Accuracy: 0.9643

Accuracy: 0.8902

-- Bidirectional LSTM (BiLSTM) for Text Classification ---
Model Type:
- A Recurrent Neural Network (RNN) using LSTM cells
- Bidirectional = it reads the sequence left-to-right and right-to-left
- Great for capturing long-range and contextual meaning

| Feature                          | Value                        |
| -------------------------------- | ---------------------------  |
| Learns word order?               | ✅ Yes                      |
| Captures context from both ends? | ✅✅ Yes (bidirectional)    |
| Handles long sentences?          | ✅ Yes                      |
| Training time?                   | 🟡 Medium (slower than CNN) |

In [30]:
from tensorflow.keras.layers import Bidirectional, LSTM

model = Sequential([
    Embedding(input_dim=vocab_size, output_dim=128, input_length=maxlen),
    Bidirectional(LSTM(64)),
    Dense(1, activation='sigmoid')
])

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
# 5. Train

model.fit(X_train_pad, y_train, epochs=5, batch_size=64, validation_split=0.1)
# 6. Evaluate
loss, acc = model.evaluate(X_test_pad, y_test)
print(f"Test Accuracy: {acc:.4f}")

Epoch 1/5
1244/1244 ━━━━━━━━━━━━━━━━━━━━ 17s 11ms/step - accuracy: 0.8765 - loss: 0.2874 - val_accuracy: 0.9720 - val_loss: 0.1159
Epoch 2/5
1244/1244 ━━━━━━━━━━━━━━━━━━━━ 23s 14ms/step - accuracy: 0.9705 - loss: 0.1174 - val_accuracy: 0.9711 - val_loss: 0.1172
Epoch 3/5
1244/1244 ━━━━━━━━━━━━━━━━━━━━ 17s 13ms/step - accuracy: 0.9723 - loss: 0.1033 - val_accuracy: 0.9724 - val_loss: 0.1178
Epoch 4/5
1244/1244 ━━━━━━━━━━━━━━━━━━━━ 17s 10ms/step - accuracy: 0.9749 - loss: 0.0851 - val_accuracy: 0.9715 - val_loss: 0.1283
Epoch 5/5
1244/1244 ━━━━━━━━━━━━━━━━━━━━ 21s 10ms/step - accuracy: 0.9786 - loss: 0.0682 - val_accuracy: 0.9690 - val_loss: 0.1305
691/691 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - accuracy: 0.9656 - loss: 0.1469
Test Accuracy: 0.9652

Accuracy: 0.8929

-- Transformers --

In [31]:
# %pip install transformers datasets tensorflow scikit-learn

In [41]:
!pip install --upgrade transformers
import transformers
print(transformers.__version__)

Requirement already satisfied: transformers in /usr/local/lib/python3.11/dist-packages (4.52.4)
Collecting transformers
  Downloading transformers-4.53.0-py3-none-any.whl.metadata (39 kB)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from transformers) (3.18.0)
Requirement already satisfied: huggingface-hub<1.0,>=0.30.0 in /usr/local/lib/python3.11/dist-packages (from transformers) (0.33.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.11/dist-packages (from transformers) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.11/dist-packages (from transformers) (24.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.11/dist-packages (from transformers) (6.0.2)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.11/dist-packages (from transformers) (2024.11.6)
Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (from transformers) (2.32.3)
Requirement already satisfied: tokenizers<0.22,>=0.21 in /usr/local/lib/python3.11/dist-packages (from transformers) (0.21.2)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.11/dist-packages (from transformers) (0.5.3)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.11/dist-packages (from transformers) (4.67.1)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub<1.0,>=0.30.0->transformers) (2025.3.2)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub<1.0,>=0.30.0->transformers) (4.14.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.2 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub<1.0,>=0.30.0->transformers) (1.1.5)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests->transformers) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests->transformers) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests->transformers) (2.4.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests->transformers) (2025.6.15)
Downloading transformers-4.53.0-py3-none-any.whl (10.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.8/10.8 MB 81.0 MB/s eta 0:00:00
Installing collected packages: transformers
  Attempting uninstall: transformers
    Found existing installation: transformers 4.52.4
    Uninstalling transformers-4.52.4:
      Successfully uninstalled transformers-4.52.4
Successfully installed transformers-4.53.0

4.52.4

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from transformers import BertTokenizer, TFBertForSequenceClassification
from transformers import InputExample, InputFeatures
import tensorflow as tf
from sklearn.metrics import accuracy_score, classification_report

# 1. Prepare your data
X = balanced_data['text'].tolist()
y = balanced_data['lashon_hara_guess'].tolist()

# 2. Split
X_train, X_test, y_train, y_test = train_test_split(X, y, stratify=y, test_size=0.2, random_state=42)

# 3. Initialize tokenizer
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')

# 4. Convert to InputExamples
def convert_data(texts, labels):
    return [InputExample(guid=str(i), text_a=txt, text_b=None, label=str(lbl)) for i, (txt, lbl) in enumerate(zip(texts, labels))]

train_examples = convert_data(X_train, y_train)
test_examples = convert_data(X_test, y_test)

# 5. Convert InputExamples to InputFeatures
def convert_examples_to_tf_dataset(examples, tokenizer, max_length=128):
    features = []

    for e in examples:
        inputs = tokenizer.encode_plus(
            e.text_a,
            add_special_tokens=True,
            max_length=max_length,
            padding='max_length',
            truncation=True,
            return_token_type_ids=False,
            return_attention_mask=True,
        )
        features.append(InputFeatures(
            input_ids=inputs['input_ids'],
            attention_mask=inputs['attention_mask'],
            label=int(e.label)
        ))

    def gen():
        for f in features:
            yield ({
                'input_ids': f.input_ids,
                'attention_mask': f.attention_mask
            }, f.label)

    return tf.data.Dataset.from_generator(
        gen,
        output_types=({'input_ids': tf.int32, 'attention_mask': tf.int32}, tf.int32),
        output_shapes=({'input_ids': (128,), 'attention_mask': (128,)}, ())
    )

train_dataset = convert_examples_to_tf_dataset(train_examples, tokenizer).shuffle(1000).batch(32)
test_dataset = convert_examples_to_tf_dataset(test_examples, tokenizer).batch(32)

# 6. Load model
model = TFBertForSequenceClassification.from_pretrained('bert-base-uncased', num_labels=2)

# 7. Train - Most robust solution using transformers optimizer
from transformers import AdamWeightDecay

# Calculate number of training steps manually since dataset length is unknown
num_train_examples = len(train_examples)
batch_size = 32
num_epochs = 3
num_train_steps = (num_train_examples // batch_size) * num_epochs

# Use transformers' AdamWeightDecay optimizer (most compatible)
optimizer = AdamWeightDecay(learning_rate=2e-5)

# Alternative approaches if the above doesn't work:
# Option 1: Try regular Adam
# optimizer = tf.keras.optimizers.Adam(learning_rate=2e-5)

# Option 2: Use create_optimizer from transformers
# from transformers import create_optimizer
# optimizer, schedule = create_optimizer(
#     init_lr=2e-5,
#     num_warmup_steps=0,
#     num_train_steps=num_train_steps
# )

# Compile with sparse categorical crossentropy since labels are integers
model.compile(
    optimizer=optimizer,
    loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
    metrics=['accuracy']
)

# Train the model
history = model.fit(
    train_dataset,
    epochs=3,
    validation_data=test_dataset,
    verbose=1
)

# 8. Evaluate
print("\nEvaluating model...")
loss, accuracy = model.evaluate(test_dataset, verbose=0)
print(f"Test accuracy: {accuracy:.4f}")

# 9. Generate predictions for more detailed evaluation
print("\nGenerating predictions...")
predictions = model.predict(test_dataset)
predicted_labels = tf.argmax(predictions.logits, axis=1).numpy()

# Print detailed classification report
print("\nClassification Report:")
print(classification_report(y_test, predicted_labels))

# 10. Improved prediction function (your version with fixes)
def predict_lashon_hara(text):
    """Predict if a text contains lashon hara - your preferred version"""
    inputs = tokenizer(text, return_tensors="tf", padding=True, truncation=True, max_length=128)
    logits = model(inputs).logits  # Access logits properly
    predicted_class = tf.argmax(logits, axis=1).numpy()[0]
    return "Lashon Hara" if predicted_class == 1 else "Not Lashon Hara"

# Alternative detailed prediction function
def predict_text_detailed(text, model, tokenizer, max_length=128):
    """Predict if a text contains lashon hara with confidence scores"""
    inputs = tokenizer.encode_plus(
        text,
        add_special_tokens=True,
        max_length=max_length,
        padding='max_length',
        truncation=True,
        return_tensors='tf'
    )

    predictions = model.predict({
        'input_ids': inputs['input_ids'],
        'attention_mask': inputs['attention_mask']
    })

    predicted_class = tf.argmax(predictions.logits, axis=1).numpy()[0]
    confidence = tf.nn.softmax(predictions.logits)[0].numpy()

    return {
        'predicted_class': int(predicted_class),
        'prediction': "Lashon Hara" if predicted_class == 1 else "Not Lashon Hara",
        'confidence_scores': {
            'not_lashon_hara': float(confidence[0]),
            'lashon_hara': float(confidence[1])
        }
    }

# Example usage:
# result = predict_lashon_hara("@josh you're the dumbest person on this app")
# print(result)
#
# detailed_result = predict_text_detailed("@josh you're the dumbest person on this app", model, tokenizer)
# print(detailed_result)

All PyTorch model weights were used when initializing TFBertForSequenceClassification.

Some weights or buffers of the TF 2.0 model TFBertForSequenceClassification were not initialized from the PyTorch model and are newly initialized: ['classifier.weight', 'classifier.bias']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Epoch 1/3
    754/Unknown - 604s 778ms/step - loss: 0.1804 - accuracy: 0.9428

In [1]:
def predict_lashon_hara(text):
    inputs = tokenizer(text, return_tensors="tf", padding=True, truncation=True, max_length=128)
    logits = model(inputs)[0]
    predicted_class = tf.argmax(logits, axis=1).numpy()[0]
    return "Lashon Hara" if predicted_class == 1 else "Not Lashon Hara"

# Example:
predict_lashon_hara("@josh you're the dumbest person on this app")

NameError: name 'tokenizer' is not defined